# Intro to numpy

In [2]:
import numpy as np

In [3]:
list1 =[3,4,5]
print(list1)
'''print simple list'''

[3, 4, 5]


'print simple list'

In [4]:
arr =np.arange(1000000)

In [5]:
pylist = list(range(1000000))

# Numpy faster than py_list
## Time complexity of numpy and py_list are as follow:

In [6]:
%time for _ in range(10) : [item * 3 for item in pylist]

Wall time: 914 ms


In [7]:
%time for _ in range(10) : arr =arr*3

Wall time: 24 ms


# Numpy_array

In [23]:
  arr1 = np.array([1,2,3,4,0.5,0.6,7,8,9,0])

In [14]:
print(arr1)
print(type(arr1))

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>


In [17]:
array1 =np.array([[1,2,3,4,5],[5,6,7,8,0]])
print(array1)
print(type(array1))

[[1 2 3 4 5]
 [5 6 7 8 0]]
<class 'numpy.ndarray'>


In [20]:
#shape of numpy array 2 rows and 5 columns
array1.shape

(2, 5)

In [21]:
# tell us about data type of numpy array
array1.dtype

dtype('int32')

In [24]:
arr1.dtype

dtype('float64')

In [27]:
arr2 = np.array([1,2,3,0.6], dtype = 'int32')

In [28]:
print(arr2)

[1 2 3 0]


In [37]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])